import java.awt.image.BufferedImage;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.EventQueue;

/**
 * Created by samuel on 27/08/15.
 */
public class CopiaArquivoGUI extends javax.swing.JFrame {
    /**
     * Creates new form CopiaArquivoGUI
     */
    public CopiaArquivoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrigem = new javax.swing.JLabel();
        btOrigem = new javax.swing.JButton();
        lblDestino = new javax.swing.JLabel();
        btDestino = new javax.swing.JButton();
        btCopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblOrigem.setText(" ");

        btOrigem.setText("Selecionar Origem");
        btOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrigemActionPerformed(evt);
            }
        });

        lblDestino.setText(" ");

        btDestino.setText("Selecionar Destino");
        btDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDestinoActionPerformed(evt);
            }
        });

        btCopiar.setText("Copiar");
        btCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(lblOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCopiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCopiar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOrigemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btOrigemActionPerformed
        // TODO add your handling code here:
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);        
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            origem = chooser.getSelectedFile();
            lblOrigem.setText(origem.getAbsolutePath());
        }
    }//GEN-LAST:event_btOrigemActionPerformed

    private void btDestinoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btDestinoActionPerformed
        // TODO add your handling code here:
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            destino = chooser.getSelectedFile();            
            lblDestino.setText(destino.getAbsolutePath());
        }
    }//GEN-LAST:event_btDestinoActionPerformed

    private void btCopiarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btCopiarActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fileInput = new FileInputStream(origem);
            FileOutputStream fileOutput = new FileOutputStream(destino.getAbsolutePath() + "/" + origem.getName());

            int bytesLidos = -1;
            byte bytes[] = new byte[16];

            while((bytesLidos = fileInput.read(bytes)) > -1){
            //while(fileInput.read(bytes) > -1){
                //System.out.print(new String(bytes));
                System.out.print(new String(bytes, 0, bytesLidos));
            }

        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopiaArquivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopiaArquivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopiaArquivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopiaArquivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(
            new Runnable() {
                public void run() {
                    new CopiaArquivoGUI().setVisible(true);
                }
            }
        );
    }

    JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
    File origem;
    File destino;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btCopiar;
    private JButton btDestino;
    private JButton btOrigem;
    private JLabel lblDestino;
    private JLabel lblOrigem;
    // End of variables declaration//GEN-END:variables
}
